package de.progresslab.bo4e.lib.enum

enum class BOTyp {
    MARKTLOKATION,
    MESSLOKATION,
    GESCHAEFTSPARTNER,
    ZAEHLER,
    ANSPRECHPARTNER,
    ANGEBOT,
    MARKTTEILNEHMER,
    ENERGIEMENGE,
    KOSTEN,
    AUSSCHREIBUNG,
    PREISBLATT,
    PREISBLATTNETZNUTZUNG,
    PREISBLATTMESSUNG,
    PREISBLATTDIENSTLEISTUNG,
    PREISBLATTUMLAGEN,
    PREISBLATTKONZESSIONSABGABE,
    TARIFINFO,
    TARIFKOSTEN,
    RECHNUNG,
    NETZNUTZUNGSRECHNUNG,
    TARIFPREISBLATT,
    REGIONALTARIF,
    ZEITREIHE
}