package de.openenwi.bo4e.lib.enum

/**
 * Über dieses ENUM kann eine thematische Zuordnung, beispielsweise eines Ansprechpartners, vorgenommen werden.
 *
 * veröffentlicht am 17. Januar 2018
 *
 * @see [ENUM Themengebiet](https://www.bo4e.de/dokumentation/enumerations/enum-zustaendigkeit)
 */
enum class Themengebiet(val beschreibung: String) {
    ALLGEMEINER_INFORMATIONSAUSTAUSCH("Allgemeiner Informationsaustausch"),
    AN_UND_ABMELDUNG("An- und Abmeldung"),
    ANSPRECHPARTNER_ALLGEMEIN("Ansprechpartner Allgemein"),
    ANSPRECHPARTNER_BDEW_DVGW("Ansprechpartner BDEW/DVGW"),
    ANSPRECHPARTNER_IT_TECHNIK("Ansprechpartner IT/Technik"),
    BILANZIERUNG("Bilanzierung"),
    BILANZKREISKOORDINATOR("Bilanzkreiskoordinator"),
    BILANZKREISVERANTWORTLICHER("Bilanzkreisverantwortlicher"),
    DATENFORMATE_ZERTIFIKATE_VERSCHLUESSELUNGEN("Datenformate, Zertifikate, Verschlüsselungen"),
    DEBITORENMANAGEMENT("Debitorenmanagement"),
    DEMAND_SIDE_MANAGEMENT("Demand-Side-Management"),
    EDI_VEREINBARUNG("EDI-Vereinbarung"),
    EDIFACT("EDIFACT"),
    ENERGIEDATENMANAGEMENT("Energiedatenmanagement"),
    FAHRPLANMANAGEMENT("Fahrplanmanagement"),
    ALOCAT("Format:ALOCAT"),
    APERAK("Format:APERAK"),
    CONTRL("Format:CONTRL"),
    INVOIC("Format:INVOIC"),
    MSCONS("Format:MSCONS"),
    ORDERS("Format:ORDERS"),
    ORDERSP("Format:ORDERSP"),
    REMADV("Format:REMADV"),
    UTILMD("Format:UTILMD"),
    GABI("GaBi Gas"),
    GELI("GeLi Gas"),
    GERAETERUECKGABE("Geräterückgabe"),
    GERAETEWECHSEL("Gerätewechsel"),
    GPKE("GPKE"),
    INBETRIEBNAHME("Inbetriebnahme"),
    KAPAZITAETSMANAGEMENT("Kapazitätsmanagement"),
    KLAERFAELLE("Klärfälle"),
    LASTGAENGE_RLM("Lastgänge RLM"),
    LIEFERANTENRAHMENVERTRAG("Lieferantenrahmenvertrag"),
    LIEFERANTENWECHSEL("Lieferantenwechsel"),
    MABIS("MaBiS"),
    MAHNWESEN("Mahnwesen"),
    MARKTGEBIETSVERANTWORTLICHER("Marktgebietsverantwortlicher"),
    MARKTKOMMUNIKATION("Marktkommunikation"),
    MEHR_MINDERMENGEN("Mehr- Mindermengen"),
    MSB_MDL("MSB - MDL"),
    NETZABRECHNUNG("Netzabrechnung"),
    NETZENTGELTE("Netzentgelte"),
    NETZMANAGEMENT("Netzmanagement"),
    RECHT("Recht"),
    REGULIERUNGSMANAGEMENT("Regulierungsmanagement"),
    REKLAMATIONEN("Reklamationen"),
    SPERREN_ENTSPERREN_INKASSO("Sperren/Entsperren/Inkasso"),
    STAMMDATEN("Stammdaten"),
    STOERUNGSFAELLE("Übermittlung_Störungsfälle"),
    TECHNISCHE_FRAGEN("Technische Fragen"),
    UMSTELLUNG_INVOIC("Umstellung INVOIC"),
    VERSCHLUESSELUNG_SIGNATUR("Verschlüsselung/Signatur"),
    VERTRAGSMANAGEMENT("Vertragsmanagement"),
    VERTRIEB("Vertrieb"),
    WIM("WiM"),
    ZAEHLERSTAENDE_SLP("Zählerstände SLP"),
    ZAHLUNGSVERKEHR("Zahlungsverkehr"),
    ZUORDNUNGSVEREINBARUNG("Zuordnungsvereinbarung"),
}
