package openenwi.bo4e.lib.enum

/**
 * Auflistung sämtlicher existierender Geschäftsobjekte.
 *
 * veröffentlicht am 17. Januar 2018
 */
enum class BOTyp {
    MARKTLOKATION,
    MESSLOKATION,
    GESCHAEFTSPARTNER,
    ZAEHLER,
    ANSPRECHPARTNER,
    ANGEBOT,
    MARKTTEILNEHMER,
    ENERGIEMENGE,
    KOSTEN,
    AUSSCHREIBUNG,
    PREISBLATT,
    PREISBLATTNETZNUTZUNG,
    PREISBLATTMESSUNG,
    PREISBLATTDIENSTLEISTUNG,
    PREISBLATTUMLAGEN,
    PREISBLATTKONZESSIONSABGABE,
    TARIFINFO,
    TARIFKOSTEN,
    RECHNUNG,
    NETZNUTZUNGSRECHNUNG,
    TARIFPREISBLATT,
    REGIONALTARIF,
    ZEITREIHE,
    // Nicht im Standard:
    LASTGANG,
    LASTGANGKOMPAKT,
    REGION,
    VERTRAG
}
